### ISSUE TITLE
#US01 - Bienvenida

### ISSUE THREAD

**Issue by EliasOro2030** [TravelDreams2024/ProyectoAppMovil#58]
-Como usuario, quiero acceder a una pantalla de bienvenida con un botón de
"Explorar" para iniciar la navegación de destinos turísticos.

*Criterios de Aceptación*

*Contexto:*
El usuario abre la aplicación en su dispositivo.

*Evento:*
El usuario visualiza la pantalla de bienvenida y tiene acceso al botón de "Explorar".

*Resultado / Comportamiento esperado:*
El botón de "Explorar" es visible y funcional, permitiendo al usuario iniciar la exploración de destinos turísticos.

*Nota al profesor: Durante los sprints 1 y 2, se irán completando los criterios de aceptación y demás ítems.

- #18  Diseñar la pantalla de bienvenida.

- #56 Implementar el botón "Explorar" que lleva a la pantalla de exploración de destinos.

- #57 Asegurar que la pantalla se ajuste bien a diferentes tamaños de dispositivos a diferentes tamaños de dispositivos.

**Comment by MaxiCantarino** [comment]
Rol: Usuario.
Características: Página de bienvenida visualmente atractiva y con fácil acceso a las funcionalidades principales.

Requerimientos de Seguridad:

    Protección de datos del usuario al iniciar la aplicación: Se implementarán medidas de seguridad que eviten la inyección de scripts maliciosos .
    Control de acceso: La aplicacion  permitirá acceso público; sin embargo, si contiene algún elemento protegido, deberá estar bajo autenticación.

Política de Seguridad Relevante:

    Protección contra XSS (Cross-Site Scripting): Se realizarán filtrados y validaciones de entradas del usuario para prevenir ataques XSS en los buscadores
